//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_HRPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.HORAS_EXTRAS = new HashSet<HORAS_EXTRAS>();
            this.VACACIONES = new HashSet<VACACIONES>();
        }
    
        public string PK_CEDULA { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime FECHA_NAC { get; set; }
        public int SALARIO { get; set; }
        public decimal SALARIO_HORA { get; set; }
        public string TIEMPO { get; set; }
        public string PUESTO { get; set; }
        public string ESTADO { get; set; }
        public int DIAS_LIBRES { get; set; }
        public string CONTRASENNA { get; set; }
        public int FK_ROL { get; set; }
        public string HORARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORAS_EXTRAS> HORAS_EXTRAS { get; set; }
        public virtual ROLES ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VACACIONES> VACACIONES { get; set; }
    }
}
