//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_HRPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACACIONES
    {
        public int PK_ID_SOLICITUD { get; set; }
        public string FK_CEDULA { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public int CANT_DIAS { get; set; }
        public string ESTADO { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
